from django.urls import path
from .views import ListChatsView, ConversationContentView, SendMessageView, ChangePasswordView, UpdateProfileImageView, LeaveProgrammeView, UpdateProgrammeView, ListProgramsView, LeaveOrganisationView, UpdateOrganisationView, JoinOrganisationView, ListOrganisationsView, UpdateEmailView, UpdateUsernameView, GetUserInfoView, UpdateNameView, CreatePostView, AddLikeView, PullPostsView, RegisterUserView, LoginUserView, ResetPasswordView, NewPasswordView, OrganisationNameView, OrganisationActivityView, ActivityContentView, ActiveTaskView, ActiveTaskContentView, CompletedTaskView, CompletedTaskContentView, ListUsersView, AddConversationView, ConversationDataView, AddLibraryView, LibraryContentView, ArticleContentView

urlpatterns = [
    path('register/', RegisterUserView.as_view(), name='register'),
    path('login/', LoginUserView.as_view(), name = 'login'),
    path('reset_password/', ResetPasswordView.as_view(), name = 'reset password'),
    path('new_password/', NewPasswordView.as_view(), name = 'new password'),
    path('organisation_name/', OrganisationNameView.as_view(), name = 'organisation name'),
    path('organisation_activity/', OrganisationActivityView.as_view(), name = 'organisation activity'),
    path('activity_content/', ActivityContentView.as_view(), name = 'activity content'),
    path('active_tasks/', ActiveTaskView.as_view(), name = 'active tasks'),
    path('active_task_content/', ActiveTaskContentView.as_view(), name = 'active task content'),
    path('completed_tasks/', CompletedTaskView.as_view(), name = 'completed tasks'),
    path('completed_task_content/', CompletedTaskContentView.as_view(), name = 'completed task content'),
    path('list_users/', ListUsersView.as_view(), name = 'list users'),
    path('add_conversation/', AddConversationView.as_view(), name = 'add conversation'),
    path('conversation_data/', ConversationDataView.as_view(), name = 'conversation data'),
    path('add_library/', AddLibraryView.as_view(), name = 'add library'),
    path('library_content/', LibraryContentView.as_view(), name = 'library content'),
    path('article_content/', ArticleContentView.as_view(), name = 'article content'),
    path('pull_posts/', PullPostsView.as_view(), name = 'pull posts'),
    path('add_like/', AddLikeView.as_view(), name = 'add like'),
    path('create_post/', CreatePostView.as_view(), name = 'create post'),
    path('update_name/', UpdateNameView.as_view(), name = 'update name'),
    path('update_email/', UpdateEmailView.as_view(), name = 'update email'),
    path('update_username/', UpdateUsernameView.as_view(), name = 'update username'),
    path('get_user_info/', GetUserInfoView.as_view(), name = 'get user info'),
    path('list_organisations/', ListOrganisationsView.as_view(), name = 'list organisations'),
    path('join_organisation/', JoinOrganisationView.as_view(), name = 'join organisation'),
    path('update_organisation/', UpdateOrganisationView.as_view(), name = 'update organisation'),
    path('leave_organisation/', LeaveOrganisationView.as_view(), name = 'leave organisation'),
    path('list_programs/', ListProgramsView.as_view(), name = 'list programs'),
    path('update_programme/', UpdateProgrammeView.as_view(), name = 'update programme'),
    path('leave_programme/', LeaveProgrammeView.as_view(), name = 'leave programme'),
    path('profile_image/', UpdateProfileImageView.as_view(), name = 'update profile image'),
    path('change_password/', ChangePasswordView.as_view(), name = 'chanege password'),
    path('send_message/', SendMessageView.as_view(), name = 'send message'),
    path('conversation_content/', ConversationContentView.as_view(), name = 'conversation_content'),
    path('list_chats/', ListChatsView.as_view(), name = 'list chats'),
]